services:
  - type: web
    name: flashread
    runtime: docker
    plan: free
    repo: https://github.com/will-king123/flashread
    branch: main
    healthCheckPath: /health
    autoDeployTrigger: commit
