services:
  - type: web
    name: flashread-app
    runtime: node
    plan: free
    repo: https://github.com/will-king123/flashread
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeployTrigger: commit
